from features import (
    achievements,
    backblast,
    canvas,
    config,
    connect,
    custom_fields,
    db_admin,
    downrange,
    emergency,
    help,
    paxminer_mapping,
    positions,
    region,
    reporting,
    special_events,
    strava,
    user,
    weaselbot,
    welcome,
)
from features.calendar import (
    ao,
    event_instance,
    event_preblast,
    event_tag,
    event_type,
    home,
    location,
    nearby_events,
    series,
)
from features.calendar import config as calendar_config
from scripts.backblast_reminders import handle_backblast_reminder_dismiss
from scripts.home_region_nudge import handle_home_region_dismiss, handle_home_region_opt_out, handle_home_region_switch
from scripts.monthly_reporting import run_reporting_single_org
from scripts.q_lineups import handle_lineup_signup
from utilities import builders, options
from utilities.slack import actions

# Required arguments for handler functions:
#     body: dict
#     client: WebClient
#     logger: Logger
#     context: dict

# The mappers define the function to be called for each event
# The first boolean value indicates whether a loading modal should be triggered before running the function
# The second boolean value indicates whether the function supports a sumbission wait view

COMMAND_MAPPER = {
    "/backblast": (backblast.backblast_middleware, True, False),
    "/preblast": (event_preblast.preblast_middleware, True, False),
    "/f3-nation-settings": (config.build_config_form, True, False),
    "/tag-achievement": (achievements.build_tag_achievement_form, True, False),
    "/f3-calendar": (home.build_home_form, True, False),
    "/help": (help.build_help_menu, False, False),
}

VIEW_MAPPER = {
    actions.BACKBLAST_CALLBACK_ID: (backblast.handle_backblast_post, False, False),
    actions.BACKBLAST_EDIT_CALLBACK_ID: (backblast.handle_backblast_post, False, False),
    actions.WELCOME_MESSAGE_CONFIG_CALLBACK_ID: (welcome.handle_welcome_message_config_post, False, False),
    actions.CONFIG_GENERAL_CALLBACK_ID: (config.handle_config_general_post, False, False),
    actions.CONFIG_EMAIL_CALLBACK_ID: (config.handle_config_email_post, False, False),
    actions.STRAVA_MODIFY_CALLBACK_ID: (strava.handle_strava_modify, False, False),
    actions.CUSTOM_FIELD_ADD_CALLBACK_ID: (custom_fields.handle_custom_field_add, False, False),
    actions.CUSTOM_FIELD_MENU_CALLBACK_ID: (custom_fields.handle_custom_field_menu, False, False),
    actions.ACHIEVEMENT_CALLBACK_ID: (achievements.handle_tag_achievement, False, False),
    actions.ACHIEVEMENT_TAG_CALLBACK_ID: (achievements.handle_tag_achievement, False, False),
    actions.ACHIEVEMENT_CONFIG_CALLBACK_ID: (achievements.handle_config_form, False, False),
    actions.ACHIEVEMENT_NEW_CALLBACK_ID: (achievements.handle_new_achievement_form, False, False),
    actions.WEASELBOT_CONFIG_CALLBACK_ID: (weaselbot.handle_config_form, False, False),
    location.ADD_LOCATION_CALLBACK_ID: (location.handle_location_add, False, False),
    actions.ADD_AO_CALLBACK_ID: (ao.handle_ao_add, False, False),
    actions.ADD_SERIES_CALLBACK_ID: (series.handle_series_add, False, False),
    actions.EVENT_PREBLAST_CALLBACK_ID: (event_preblast.handle_event_preblast_edit, False, True),
    event_type.CALENDAR_ADD_EVENT_TYPE_CALLBACK_ID: (event_type.handle_event_type_add, False, False),
    actions.REGION_CALLBACK_ID: (region.handle_region_edit, False, False),
    actions.SPECIAL_EVENTS_CALLBACK_ID: (special_events.handle_special_settings_edit, False, False),
    actions.CONFIG_SLT_CALLBACK_ID: (positions.handle_config_slt_post, False, False),
    actions.NEW_POSITION_CALLBACK_ID: (positions.handle_new_position_post, False, False),
    actions.EDIT_POSITION_CALLBACK_ID: (positions.handle_edit_position_post, False, False),
    connect.CONNECT_EXISTING_REGION_CALLBACK_ID: (connect.handle_existing_region_selection, False, False),
    connect.CREATE_NEW_REGION_CALLBACK_ID: (connect.handle_new_region_creation, False, False),
    actions.CALENDAR_CONFIG_GENERAL_CALLBACK_ID: (calendar_config.handle_calendar_config_general, False, False),
    user.USER_FORM_ID: (user.handle_user_form, False, False),
    event_instance.ADD_EVENT_INSTANCE_CALLBACK_ID: (event_instance.handle_event_instance_add, False, False),
    event_tag.CALENDAR_ADD_EVENT_TAG_CALLBACK_ID: (event_tag.handle_event_tag_add, False, False),
    actions.HOME_ASSIGN_Q_CALLBACK_ID: (home.handle_assign_q_form, False, False),
    actions.DB_ADMIN_CALLBACK_ID: (db_admin.handle_send_admin_announcement, False, False),
    reporting.REPORTING_CALLBACK_ID: (reporting.handle_reporting_edit, False, False),
    actions.DB_ADMIN_LONG_RUN_CALLBACK_ID: (db_admin.handle_long_run_task, False, False),
    paxminer_mapping.PAXMINER_MAPPING_ID: (paxminer_mapping.handle_paxminer_mapping_post, False, False),
    event_instance.EVENT_CLOSE_CALLBACK_ID: (event_instance.handle_event_instance_close, False, False),
    actions.EVENT_CLOSE_HOME_CALLBACK_ID: (home.handle_event_instance_close, False, False),
    actions.DOWNRANGE_CALLBACK_ID: (downrange.handle_downrange_settings, False, False),
}

ACTION_MAPPER = {
    actions.BACKBLAST_EDIT_BUTTON: (backblast.handle_backblast_edit_button, True, False),
    actions.BACKBLAST_EDIT_BUTTON_LEGACY: (backblast.handle_legacy_edit_button, True, False),
    actions.BACKBLAST_NEW_BUTTON: (backblast.backblast_middleware, True, False),
    actions.BACKBLAST_STRAVA_BUTTON: (strava.build_strava_form, True, False),
    actions.STRAVA_ACTIVITY_BUTTON: (strava.build_strava_modify_form, False, False),
    actions.STRAVA_CONNECT_BUTTON: (builders.ignore_event, False, False),
    actions.CONFIG_CUSTOM_FIELDS: (custom_fields.build_custom_field_menu, False, False),
    actions.CUSTOM_FIELD_ADD: (custom_fields.build_custom_field_add_edit, False, False),
    actions.CUSTOM_FIELD_EDIT: (custom_fields.build_custom_field_add_edit, False, False),
    actions.CUSTOM_FIELD_DELETE: (custom_fields.delete_custom_field, False, False),
    actions.PREBLAST_NEW_BUTTON: (event_preblast.preblast_middleware, True, False),
    actions.CONFIG_WEASELBOT: (weaselbot.build_config_form, False, False),
    actions.CONFIG_ACHIEVEMENTS: (achievements.build_config_form, False, False),
    actions.ACHIEVEMENT_CONFIG_NEW_BTN: (achievements.build_new_achievement_form, False, False),
    actions.ACHIEVEMENT_CONFIG_MANAGE_BTN: (achievements.build_manage_achievements_form, False, False),
    actions.ACHIEVEMENT_MANAGE_OVERFLOW: (achievements.handle_manage_overflow, False, False),
    actions.CONFIG_WELCOME_MESSAGE: (welcome.build_welcome_message_form, False, False),
    actions.CONFIG_EMAIL: (config.build_config_email_form, False, False),
    actions.CONFIG_GENERAL: (config.build_config_general_form, False, False),
    actions.CONFIG_WELCOME_MESSAGE: (welcome.build_welcome_config_form, False, False),
    actions.CONFIG_CALENDAR: (calendar_config.build_calendar_config_form, False, False),
    actions.CALENDAR_ADD_SERIES_AO: (series.build_series_add_form, False, False),
    actions.SERIES_EDIT_DELETE: (series.handle_series_edit_delete, False, False),
    location.LOCATION_EDIT_DELETE: (location.handle_location_edit_delete, False, False),
    actions.AO_EDIT_DELETE: (ao.handle_ao_edit_delete, False, False),
    actions.CALENDAR_ADD_EVENT_AO: (series.build_series_add_form, False, False),
    location.CALENDAR_MANAGE_LOCATIONS: (location.manage_locations, False, False),
    actions.CALENDAR_MANAGE_AOS: (ao.manage_aos, False, False),
    actions.CALENDAR_MANAGE_SERIES: (series.manage_series, False, False),
    actions.CALENDAR_MANAGE_EVENTS: (series.manage_series, False, False),
    event_type.CALENDAR_MANAGE_EVENT_TYPES: (event_type.manage_event_types, False, False),
    location.CALENDAR_ADD_AO_NEW_LOCATION: (location.build_location_add_form, False, False),
    actions.CALENDAR_HOME_EVENT: (home.handle_home_event, False, False),
    actions.CALENDAR_HOME_AO_FILTER: (home.build_home_form, False, False),
    actions.CALENDAR_HOME_Q_FILTER: (home.build_home_form, False, False),
    actions.CALENDAR_HOME_DATE_FILTER: (home.build_home_form, False, False),
    actions.CALENDAR_HOME_EVENT_TYPE_FILTER: (home.build_home_form, False, False),
    actions.EVENT_PREBLAST_HC: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_UN_HC: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_TAKE_Q: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_REMOVE_Q: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_HC_UN_HC: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_EDIT: (event_preblast.handle_event_preblast_action, False, False),
    actions.EVENT_PREBLAST_SELECT: (event_preblast.handle_event_preblast_select, False, False),
    actions.EVENT_PREBLAST_NEW_BUTTON: (home.handle_event_preblast_select_button, False, False),
    actions.OPEN_CALENDAR_BUTTON: (home.handle_event_preblast_select_button, True, False),
    actions.MSG_EVENT_PREBLAST_BUTTON: (event_preblast.handle_event_preblast_action, False, False),
    actions.MSG_EVENT_BACKBLAST_BUTTON: (backblast.backblast_middleware, True, False),
    actions.MSG_EVENT_BACKBLAST_ALREADY_BUTTON: (handle_backblast_reminder_dismiss, False, False),
    actions.BACKBLAST_FILL_SELECT: (backblast.build_backblast_form, True, False),
    actions.BACKBLAST_NEW_BLANK_BUTTON: (backblast.build_backblast_form, True, False),
    actions.REGION_INFO_BUTTON: (region.build_region_form, False, False),
    actions.CONFIG_SPECIAL_EVENTS: (special_events.build_special_settings_form, False, False),
    actions.SECRET_MENU_CALENDAR_IMAGES: (db_admin.handle_calendar_image_refresh, False, False),
    actions.CONFIG_SLT: (positions.build_config_slt_form, True, False),
    actions.SLT_LEVEL_SELECT: (positions.build_config_slt_form, False, False),
    actions.CONFIG_NEW_POSITION: (positions.build_new_position_form, False, False),
    actions.CONFIG_EDIT_POSITIONS: (positions.build_position_list_form, False, False),
    actions.POSITION_EDIT_DELETE: (positions.handle_position_edit_delete, False, False),
    actions.CONFIG_CONNECT: (connect.build_connect_options_form, False, False),
    connect.CONNECT_EXISTING_REGION: (connect.build_existing_region_form, False, False),
    connect.CREATE_NEW_REGION: (connect.build_new_region_form, False, False),
    actions.SECRET_MENU_UPDATE_CANVAS: (canvas.update_canvas, False, False),
    actions.SECRET_MENU_MAKE_ADMIN: (db_admin.handle_make_admin, False, False),
    actions.SECRET_MENU_MAKE_ORG: (db_admin.handle_make_org, False, False),
    actions.CALENDAR_CONFIG_GENERAL: (calendar_config.build_calendar_general_config_form, False, False),
    actions.SECRET_MENU_AO_LINEUPS: (db_admin.handle_ao_lineups, False, False),
    actions.OPEN_CALENDAR_MSG_BUTTON: (home.build_home_form, True, False),
    actions.SECRET_MENU_PREBLAST_REMINDERS: (db_admin.handle_preblast_reminders, False, False),
    actions.SECRET_MENU_BACKBLAST_REMINDERS: (db_admin.handle_backblast_reminders, False, False),
    actions.LINEUP_SIGNUP_BUTTON: (handle_lineup_signup, False, False),
    actions.SECRET_MENU_TRIGGER_MAP_REVALIDATION: (db_admin.handle_trigger_map_revalidation, False, False),
    actions.CONFIG_USER_SETTINGS: (user.build_user_form, True, False),
    event_instance.CALENDAR_MANAGE_EVENT_INSTANCE: (event_instance.manage_event_instances, False, False),
    actions.EVENT_INSTANCE_EDIT_DELETE: (event_instance.handle_event_instance_edit_delete, False, False),
    event_instance.CALENDAR_ADD_EVENT_INSTANCE_AO: (event_instance.build_event_instance_add_form, False, False),
    event_instance.CALENDAR_MANAGE_EVENT_INSTANCE_AO: (event_instance.build_event_instance_list_form, False, False),
    event_instance.CALENDAR_MANAGE_EVENT_INSTANCE_DATE: (event_instance.build_event_instance_list_form, False, False),
    event_type.EVENT_TYPE_EDIT_DELETE: (event_type.handle_event_type_edit_delete, False, False),
    actions.OPEN_CALENDAR_IMAGE_BUTTON: (home.build_calendar_image_form, False, False),
    event_tag.EVENT_TAG_EDIT_DELETE: (event_tag.handle_event_tag_edit_delete, False, False),
    event_tag.CALENDAR_MANAGE_EVENT_TAGS: (event_tag.manage_event_tags, False, False),
    actions.SECRET_MENU_REFRESH_SLACK_USERS: (db_admin.handle_slack_user_refresh, False, False),
    actions.SECRET_MENU_UPDATE_BOT_TOKEN: (db_admin.handle_update_bot_token, False, False),
    connect.DENY_CONNECTION: (connect.handle_deny_connection, False, False),
    connect.APPROVE_CONNECTION: (connect.handle_approve_connection, False, False),
    user.IGNORE_EVENT: (builders.ignore_event, False, False),
    actions.CONFIG_REPORTING: (reporting.build_reporting_form, False, False),
    reporting.RUN_MONTHLY_REPORTS_NOW: (run_reporting_single_org, False, False),
    actions.CONFIG_HELP_MENU: (help.build_help_menu, False, False),
    actions.CALENDAR_MANAGE_SERIES_AO: (series.build_series_list_form, False, False),
    actions.SETTINGS_BUTTON: (config.build_config_form, True, False),
    actions.SECRET_MENU_LONG_RUN: (db_admin.build_long_run_task_form, False, False),
    actions.PAXMINER_MAPPING: (paxminer_mapping.build_paxminer_mapping_form, False, False),
    paxminer_mapping.PAXMINER_ORIGINATING_CHANNEL: (paxminer_mapping.build_paxminer_mapping_form, False, False),
    paxminer_mapping.PAXMINER_REGION: (paxminer_mapping.build_paxminer_mapping_form, False, False),
    actions.PREBLAST_FILL_BACKBLAST_BUTTON: (backblast.backblast_middleware, True, False),
    actions.NEW_PREBLAST_BUTTON: (event_preblast.preblast_middleware, True, False),
    actions.BACKBLAST_NOQ_SELECT: (backblast.build_backblast_form, True, False),
    actions.BACKBLAST_FILL_BUTTON: (backblast.build_backblast_form, True, False),
    actions.EVENT_PREBLAST_FILL_BUTTON: (event_preblast.handle_event_preblast_select, False, False),
    actions.PREBLAST_OVERFLOW_ACTION: (event_preblast.route_preblast_overflow_action, False, False),
    actions.SECRET_MENU_SEND_AUTO_PREBLASTS: (db_admin.handle_auto_preblast_send, False, False),
    actions.SECRET_MENU_REFRESH_CACHE: (db_admin.handle_refresh_cache, False, False),
    actions.CONFIG_EMERGENCY_INFO: (emergency.build_emergency_search_form, True, False),
    actions.EMERGENCY_LOCAL_USER_SELECT: (emergency.handle_local_user_select, False, False),
    actions.EMERGENCY_DR_USER_SELECT: (emergency.handle_dr_user_select, False, False),
    actions.CONFIG_DOWNRANGE: (downrange.build_downrange_menu, True, False),
    actions.DOWNRANGE_REGION_SELECT: (downrange.handle_region_select, False, False),
    actions.DOWNRANGE_INVITE_REQUEST_BUTTON: (downrange.handle_invite_request, False, False),
    actions.DOWNRANGE_INVITE_APPROVE_BUTTON: (downrange.handle_invite_approve, False, False),
    actions.DOWNRANGE_INVITE_DENY_BUTTON: (downrange.handle_invite_deny, False, False),
    actions.DOWNRANGE_INVITE_LINK_BROKEN_BUTTON: (downrange.handle_invite_link_broken, False, False),
    actions.DOWNRANGE_INVITE_MARK_DONE_BUTTON: (downrange.handle_invite_mark_done, False, False),
    actions.HOME_REGION_NUDGE_SWITCH_BUTTON: (handle_home_region_switch, False, False),
    actions.HOME_REGION_NUDGE_DISMISS_BUTTON: (handle_home_region_dismiss, False, False),
    actions.HOME_REGION_NUDGE_OPT_OUT_BUTTON: (handle_home_region_opt_out, False, False),
    actions.NEARBY_EVENTS_OPEN: (nearby_events.build_nearby_events_modal, False, False),
    actions.NEARBY_EVENTS_DISTANCE: (nearby_events.build_nearby_events_modal, False, False),
    actions.NEARBY_EVENTS_SORT: (nearby_events.build_nearby_events_modal, False, False),
    actions.NEARBY_EVENTS_HC: (nearby_events.handle_nearby_events_hc_action, False, False),
    actions.NEARBY_EVENTS_UN_HC: (nearby_events.handle_nearby_events_hc_action, False, False),
    actions.MISSING_BACKBLASTS_BUTTON: (backblast.build_missing_backblasts_form, True, False),
    actions.MISSING_BACKBLASTS_AO_FILTER: (backblast.build_missing_backblasts_form, False, False),
    actions.MISSING_BACKBLASTS_EVENT: (backblast.handle_missing_backblasts_overflow, False, False),
}

ACTION_PREFIXES = [
    actions.STRAVA_ACTIVITY_BUTTON,
    actions.SERIES_EDIT_DELETE,
    location.LOCATION_EDIT_DELETE,
    actions.AO_EDIT_DELETE,
    actions.CALENDAR_HOME_EVENT,
    actions.BACKBLAST_FILL_SELECT,
    actions.LINEUP_SIGNUP_BUTTON,
    actions.EVENT_INSTANCE_EDIT_DELETE,
    event_type.EVENT_TYPE_EDIT_DELETE,
    event_tag.EVENT_TAG_EDIT_DELETE,
    actions.BACKBLAST_FILL_BUTTON,
    actions.EVENT_PREBLAST_FILL_BUTTON,
    actions.POSITION_EDIT_DELETE,
    actions.MISSING_BACKBLASTS_EVENT,
    actions.ACHIEVEMENT_MANAGE_OVERFLOW,
]

VIEW_CLOSED_MAPPER = {
    actions.CUSTOM_FIELD_ADD_FORM: (builders.ignore_event, False, False),
    actions.STRAVA_MODIFY_CALLBACK_ID: (strava.handle_strava_modify, False, False),
}

EVENT_MAPPER = {
    "team_join": (welcome.handle_team_join, False, False),
    "app_mention": (help.handle_app_mention, False, False),
}

OPTIONS_MAPPER = {
    actions.USER_OPTION_LOAD: (options.handle_request, False, False),
    user.USER_FORM_HOME_REGION: (options.handle_request, False, False),
    user.USER_FORM_BROUGHT_BY: (options.handle_request, False, False),
    paxminer_mapping.PAXMINER_REGION: (options.handle_request, False, False),
    connect.SELECT_REGION: (options.handle_request, False, False),
    actions.EMERGENCY_DR_USER_SELECT: (options.handle_request, False, False),
    actions.DOWNRANGE_REGION_SELECT: (options.handle_request, False, False),
}

SHORTCUT_MAPPER = {
    actions.BACKBLAST_SHORTCUT: (backblast.backblast_middleware, True, False),
    actions.PREBLAST_SHORTCUT: (event_preblast.preblast_middleware, True, False),
    actions.CALENDAR_SHORTCUT: (home.build_home_form, True, False),
    actions.SETTINGS_SHORTCUT: (config.build_config_form, True, False),
    actions.TAG_ACHIEVEMENT_SHORTCUT: (achievements.build_tag_achievement_form, True, False),
}

MAIN_MAPPER = {
    "command": COMMAND_MAPPER,
    "block_actions": ACTION_MAPPER,
    "view_submission": VIEW_MAPPER,
    "view_closed": VIEW_CLOSED_MAPPER,
    "event_callback": EVENT_MAPPER,
    "block_suggestion": OPTIONS_MAPPER,
    "shortcut": SHORTCUT_MAPPER,
}
